[package]
name = "tx-indexer-primitives"
version = "0.1.0"
edition = "2024"

[features]
integration-test = []

[dependencies]
bitcoin = {workspace = true}
bitcoin_slices = { workspace = true, features = ["bitcoin"]}

[dev-dependencies]
anyhow = "1.0"
corepc-node = { version = "0.10", features = ["download", "22_1"] }
