[package]
name = "heuristics"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true }
tx-indexer-primitives = { path = "../primitives" }
pipeline = { path = "../pipeline" }

[dev-dependencies]
rand = "0.8.5"
